In [1]:
print("hello world")

hello world


In [3]:
import numpy as np

In [5]:
mylist = [1,2,3,4] 

In [6]:
type(mylist)

list

In [8]:
myarray = np.array(mylist)

In [9]:
type(myarray)

numpy.ndarray

In [10]:
np.arange(2,10,2)

array([2, 4, 6, 8])

In [11]:
np.zeros(shape=(5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [16]:
np.random.seed(100)

In [17]:
arr=np.random.randint(0,100,10)

In [21]:
arr

array([ 8, 24, 67, 87, 79, 48, 10, 94, 52, 98])

In [23]:
arr.min()

8

In [24]:
arr.max()

98

In [25]:
arr.mean()

56.7

In [26]:
arr.reshape((2,5))

array([[ 8, 24, 67, 87, 79],
       [48, 10, 94, 52, 98]])